const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('neorang-intro-seen-v1','1'));
 await page.goto('http://localhost:5500/index.html');await page.waitForSelector('#kakao-map');
 await page.locator('.map-rail [data-workspace=browse]').click();assert.equal(await page.locator('.workspace-trip-card').count(),10);assert.equal(await page.locator('.workspace-trip-card img').count(),10);assert.equal(await page.locator('[data-card-mode]').count(),0);assert.equal(await page.getByText('상세·참가',{exact:true}).count(),0);
 await page.screenshot({path:process.cwd()+'/docs/screenshots/12-travel-card-list.png'});
 await page.locator('[data-select-trip="2"]').click();assert.equal(await page.locator('.workspace-trip-card').count(),0);assert.equal(await page.locator('.workspace-detail-button').innerText(),'세부내용 보기');await page.waitForSelector('.companion-route-marker');
 await page.evaluate(()=>{const Original=kakao.maps.Polyline;window.routeStyles=[];kakao.maps.Polyline=function(options){window.routeStyles.push({color:options.strokeColor,style:options.strokeStyle,length:options.path.length});return new Original(options)};kakao.maps.Polyline.prototype=Original.prototype;});
 await page.locator('[data-workspace-mode=car]').click();await page.waitForFunction(()=>document.querySelector('#workspace-route-status').textContent.includes('실제 차량 경로'),{timeout:30000});assert.ok(await page.evaluate(()=>routeStyles.at(-1).color==='#dc3545'&&routeStyles.at(-1).style==='solid'&&routeStyles.at(-1).length>3));assert.equal(await page.locator('[data-workspace-mode=car]').getAttribute('aria-pressed'),'true');
 await page.locator('[data-workspace-day="2"]').click();assert.equal(await page.locator('[data-workspace-mode=car]').getAttribute('aria-pressed'),'true');await page.locator('[data-workspace-day="1"]').click();await page.locator('[data-workspace-mode=straight]').click();assert.equal(await page.locator('[data-workspace-mode=straight]').getAttribute('aria-pressed'),'true');await page.waitForTimeout(1000);await page.screenshot({path:process.cwd()+'/docs/screenshots/13-focused-travel.png'});
 await page.locator('.workspace-detail-button').click();await page.waitForURL('**/companion-detail.html?id=2');await page.goto('http://localhost:5500/index.html');await page.evaluate(()=>{const key='neorang-galjido-v1',s=JSON.parse(localStorage.getItem(key));s.loggedIn=true;s.user=s.members[0];localStorage.setItem(key,JSON.stringify(s));});await page.reload();await page.locator('.map-rail [data-workspace=mine]').click();await page.locator('[data-select-trip="seed-plan-1"]').click();assert.equal(await page.locator('.workspace-trip-card').count(),0);await page.locator('#workspace-plan-detail').click();await page.waitForURL('**/planner.html');assert.equal(await page.locator('#plan-title').inputValue(),'제주 바다와 카페를 천천히');assert.equal(await page.locator('.schedule-row').count(),3);
 await page.goto('http://localhost:5500/index.html');await page.locator('.map-rail [data-workspace=mine]').click();await page.locator('#workspace-new').click();await page.waitForURL('**/planner.html');assert.equal(await page.locator('#plan-title').inputValue(),'새로운 여행');assert.equal(await page.locator('.schedule-row').count(),0);await page.reload();assert.equal(await page.locator('#plan-title').inputValue(),'새로운 여행');
 await page.setViewportSize({width:390,height:900});await page.goto('http://localhost:5500/index.html');await page.locator('.map-rail [data-workspace=browse]').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('[data-select-trip="2"]').click();assert.equal(await page.locator('.workspace-trip-card').count(),0);await page.screenshot({path:process.cwd()+'/docs/screenshots/mobile-focused-travel.png'});await page.locator('#workspace-back').click();assert.equal(await page.locator('.workspace-trip-card').count(),10);await page.locator('#workspace-close').click();assert.ok(await page.locator('.search-panel').evaluate(node=>!node.classList.contains('is-open')));assert.deepEqual(errors,[]);
 console.log('PASS image cards; focused trip and back; red actual car/straight routes; toggles preserve DAY; details links restore correct plan; fresh planner navigation and reload; 390px mobile; no JS errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
